### ISSUE TITLE
How is the chat technically implemented ? 

### ISSUE THREAD

**Issue by jprudent** [pinnaculum/galacteek#24]
Hello, this is not an issue perse but much more a question. I don't want to take too much of your time... Feel free to close this issue if you find it inappropriate, I would take no offence. 
in the readme you say chat channels syncronized with CRDT+DAG
I'm trying to design an ipfs application where peers would collaboratively change the state of a bunch of data. I'm not sure but it looks like CRDT would the solution to my problem.
Could you, if that's not bothering you, explain in technical terms the big picture behind "I retrieve the channel list with CRDT and Dag". Thanks a lot.

**Comment by pinnaculum** [comment]
No problem at all, not inappropriate, i'll try to answer
and will probably put the infos in the wiki later. I'm
no expert at all on DAGs or CRDT :)

So it's quite simple actually .. each galacteek peer
stores the list of chat channels in a raw IPFS DAG. The
way it's stored doesn't matter much but maybe this helps:

`
  {
  "channels": {
      "all": [
        "#galacteek",
        "#testing"
      ]
    }
}
`

Each peer, via a pubsub message (JSON), periodically sends
their version of the channels list to the network. The other
peers, on getting the message, merge the received channels
list with their channels list, using CRDT (it's implemented
[here](https://github.com/pinnaculum/galacteek/blob/master/galacteek/core/edags/chatchannels.py#L51).)

So imagine there are three peers, Peer A, B and C and they have
the same channels list (2 channels, the example i gave above).
Peer A adds a channel (say #ipfs) and sends the channels list
via pubsub. Both peers B and C receive the new list via pubsub.
The CRDT merge will result in peers B and C adding #ipfs to
their list of channels (they only had #galacteek and #testing
before receiving the message), and so all peers now have the
same list of channels, stored in a DAG.

Using a DAG for storage has no drawbacks here, and in the future
probably the pubsub message will only reference the DAG's CID
to save bandwidth (letting other peers fetch the DAG's content).

So for what you want to do, definitely you can use pubsub + CRDT,
and use IPFS DAGs for storage, but it all depends on your data..
See [CRDT on wikipedia](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type) 

Hope this answers your question.

**Comment by jprudent** [comment]
Many thanks! This is a great answer. I'll dive a bit in CRDT.

I have a question though. If a peer is not online and miss an update on pubsub. Does it retrieve the whole list of channels in the DAG on startup ?

**Comment by pinnaculum** [comment]
If a peer isn't online for a period of time and misses one or more updates to the list, on startup of course he won't have the full list, but once it receives a channels list message from a peer he'll have the same list as everyone. Forgot to mention that the CRDT used is a Gset (grow-only) so you can't lose channels.

All in all this system works decently in most cases but because everyone persists their copy in their repository (and not in some blockchain for example), the worst-case scenario would be: say there are maybe 20 peers on the network, the channels list grows, they have all the same list. Then all these peers go offline and don't reconnect for a long period of time. Now a new peer, with an empty channels list (never connected) goes online: no node of the previous group of 20 peers is online to give him a list, so he's left with nothing :)

You should take a look at [Orbit-DB](https://github.com/orbitdb/orbit-db) it's an amazing project, it's a distributed P2P database, they also use pubsub and CRDT.

**Comment by jprudent** [comment]
Thank you very much for your invaluable insights. This will be of great help. Thanks again 👍
