### ISSUE TITLE
Windows Installer / Package

### ISSUE THREAD

**Issue by tiksn** [pinnaculum/galacteek#25]
Large portion of users use Windows. If this project needs to garner support from all users and not only from technically savvy IPFS enthusiasts it needs to have Windows installer and/or package like WinGet, Chocolatey, Scoop.

**Comment by pinnaculum** [comment]
Hello @tiksn,

Obviously you're right (although the project is not aimed at technically savvy persons) there should ideally be an installer for this platform (managed to package it with pyinstaller from travis but don't think it would run). I don't have access to anything else but Linux machines and it's not exactly a priority at the moment.

If you use something like windows 10 and want to help on this, that would be much appreciated. The issue is not exactly the usage of asyncio/quamash i think but rather running subprocesses (in this case go-ipfs) with the ProactorEventLoop ([some documentation here](https://docs.python.org/dev/library/asyncio-platforms.html#windows)). Would be good to test it with python 3.8.

**Comment by pinnaculum** [comment]
Build instructions can be found [here](https://github.com/pinnaculum/galacteek/blob/master/BUILDING.rst). If you manage to make it run, or find a fix to make it run, please report it here :)

**Comment by pinnaculum** [comment]
Just giving an update on this issue .. galacteek now works on windows, also the CI workflow now builds a windows executable (with pyinstaller at the moment). The windows bundle's size is substantially larger (~280 Mb) but this can be optimized by removing unnecessary modules and Qt5 data files in the CI job's virtual env. As with most pyinstaller one-file bundles, loading time is a bit slow because it has to unpack the self-contained archive to a temporary folder, using a zip archive instead of one-file is also an option.

There are no major issues, apart from some small problems with the mediaplayer, i'll create a separate issue for that.

**Comment by pinnaculum** [comment]
Starting with the [0.4.39 release](https://github.com/pinnaculum/galacteek/releases/tag/v0.4.39) there's now a NSIS installer for windows. The console window when starting the browser is normal and is hidden after startup (will stay this way at least until #33 is fixed).

Please report any issues/requests with the windows installer here.
