### ISSUE TITLE
UnPin Feature

### ISSUE THREAD

**Issue by TheDiscordian** [pinnaculum/galacteek#34]
Currently it's extremely easy to pin things on galacteek. I was wondering if the inverse could also be true? Could galacteek log what it pins, so for example if you pinned a whole website, there could be an item to then unpin the whole website. I spent a while looking for such a feature, and I think that'd be a really cool addition.

## Software version
0.4.41

## OS
Manjaro Linux

## IPFS daemon type (standalone/custom)

- [x] Standalone
- [ ] Custom IPFS daemon

**Comment by pinnaculum** [comment]
> Currently it's extremely easy to pin things on galacteek. I was wondering if the inverse could also be true? Could galacteek log what it pins, so for example if you pinned a whole website, there could be an item to then unpin the whole website. I spent a while looking for such a feature, and I think that'd be a really cool addition.

Hello @TheDiscordian and thanks for raising the issue.

There's no real need for "logging" (i suppose in that sense you mean *recording*) what the application pins, since *go-ipfs* already does that, and has an API to query what is pinned in the repository, as well as unpin a specific object. Because listing pinned objects can be costly in CPU and time on the daemon, there'll probably be a caching system implemented, to have a live *picture* of what's pinned.

It would indeed be a very useful feature and it will be available in some form starting with the *0.5.0* release. I'd like the *pinned* status of pages, etc .. reflected almost in real time.

I'll keep you posted, thanks again and feel free to suggest any other features that you think of.

**Comment by pinnaculum** [comment]
The *0.5.0* release introduced support for remote pinning, as well as the possibility to unpin content (*remote* or *local*). In the future, the *Unpin* actions will only be usable/visible when the content is already pinned on the targeted node.
